import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs/promises';
import path from 'node:path';

const execFileAsync = promisify(execFile);
const DEFAULT_OUTPUT_FPS = 20;

// Session frames are JPEGs, not a video container. Build a broadly playable
// H.264 MP4 only after the session has finished uploading.
export async function createSessionVideo({ dataDir, sessionId, frames, fps = DEFAULT_OUTPUT_FPS }) {
  if (!frames.length) throw new Error('session has no frames');
  const sessionDir = path.join(dataDir, String(sessionId));
  const outputPath = path.join(sessionDir, 'session.mp4');
  const manifestPath = path.join(sessionDir, '.frames.ffconcat');
  await fs.mkdir(sessionDir, { recursive: true });
  const outputFps = Math.min(Math.max(Number(fps) || DEFAULT_OUTPUT_FPS, 1), 60);
  const frameDuration = 1 / outputFps;
  const lines = ['ffconcat version 1.0'];
  for (const frame of frames) {
    // The session filenames are generated by the server. Relative paths avoid
    // FFmpeg concat escaping problems when DATA_DIR contains an apostrophe.
    lines.push(`file '${frame.path}'`);
    lines.push(`duration ${frameDuration}`);
  }
  // The concat demuxer uses the final file's duration only when it is repeated.
  lines.push(`file '${frames.at(-1).path}'`);
  await fs.writeFile(manifestPath, `${lines.join('\n')}\n`);
  try {
    await execFileAsync('ffmpeg', [
      '-y', '-f', 'concat', '-safe', '0', '-i', manifestPath,
      '-vf', `fps=${outputFps}`, '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
      '-movflags', '+faststart', outputPath,
    ], { cwd: sessionDir });
  } finally {
    await fs.rm(manifestPath, { force: true });
  }
  return outputPath;
}

export async function createAviVideo({ aviPath, outputPath }) {
  await execFileAsync('ffmpeg', [
    '-y', '-i', aviPath, '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
    '-movflags', '+faststart', outputPath,
  ]);
  return outputPath;
}
